How the Perceptron Algorithm Works




Input values/One input layer

Weights and Bias

Net Sum

Activation Function

Create a perceptron to demonstrate the following
a. AND operation
b. OR operation
c. XOR operation

1 NOT



In [ ]:
import numpy as np

def unit_step(v):
	if v >= 0:
		return 1
	else:
		return 0
	
def perceptron(x, w, b):
	v = np.dot(w, x) + b
	y = unit_step(v)
	return y

def NOT_percep(x):
	return perceptron(x, w=-1, b=0.5)

print("NOT(0) = {}".format(NOT_percep(0)))
print("NOT(1) = {}".format(NOT_percep(1)))

NOT(0) = 1
NOT(1) = 0


2 AND

In [ ]:
def AND_percep(x):
    w = np.array([1, 1])
    b = -1.5
    return perceptron(x, w, b)

# Test
example1 = np.array([1, 1])
example2 = np.array([1, 0])
example3 = np.array([0, 1])
example4 = np.array([0, 0])

l1= [example1, example2,example3, example4]

target=[1,0,0,0]

actual=[]
for i in l1:
  x = AND_percep(i)
  actual.append(x)

for i in actual:
  error=target[i]-actual[i]
  print(f"Eror: \n{error}")
print("AND({}, {}) = {}".format(1, 1, AND_percep(example1)))
print("AND({}, {}) = {}".format(1, 0, AND_percep(example2)))
print("AND({}, {}) = {}".format(0, 1, AND_percep(example3)))
print("AND({}, {}) = {}".format(0, 0, AND_percep(example4)))

Eror: 
0
Eror: 
0
Eror: 
0
Eror: 
0
AND(1, 1) = 1
AND(1, 0) = 0
AND(0, 1) = 0
AND(0, 0) = 0


3 OR

In [ ]:
def OR_percep(x):
    w = np.array([1, 1])
    b = -0.5
    return perceptron(x, w, b)

# Test
example1 = np.array([1, 1])
example2 = np.array([1, 0])
example3 = np.array([0, 1])
example4 = np.array([0, 0])

l1= [example1, example2,example3, example4]

target=[1,1,1,0]

actual=[]
for i in l1:
  x = OR_percep(i)
  actual.append(x)

for i in actual:
  error=target[i]-actual[i]
  print(f"Eror: \n{error}")
print("OR({}, {}) = {}".format(1, 1, OR_percep(example1)))
print("OR({}, {}) = {}".format(1, 0, OR_percep(example2)))
print("OR({}, {}) = {}".format(0, 1, OR_percep(example3)))
print("OR({}, {}) = {}".format(0, 0, OR_percep(example4)))

Eror: 
0
Eror: 
0
Eror: 
0
Eror: 
0
OR(1, 1) = 1
OR(1, 0) = 1
OR(0, 1) = 1
OR(0, 0) = 0


In [ ]:
def XOR_net(x):
    gate_1 = AND_percep(x)
    gate_2 = NOT_percep(gate_1)
    gate_3 = OR_percep(x)
    new_x = np.array([gate_2, gate_3])
    output = AND_percep(new_x)
    return output

print("XOR({}, {}) = {}".format(1, 1, XOR_net(example1)))
print("XOR({}, {}) = {}".format(1, 0, XOR_net(example2)))
print("XOR({}, {}) = {}".format(0, 1, XOR_net(example3)))
print("XOR({}, {}) = {}".format(0, 0, XOR_net(example4)))

XOR(1, 1) = 0
XOR(1, 0) = 1
XOR(0, 1) = 1
XOR(0, 0) = 0


First, its output values can only take two possible values, 0 or 1.

Secondly, the Perceptron can only be used to classify linear separable vector sets. According to the perceptron convergence theorem, the perceptron learning rule guarantees to find a solution within a finite number of steps if the provided data set is linearly separable.

In [ ]:
from numpy import array, random, dot

from random import choice

In [ ]:
step_function = lambda x: 0 if x < 0 else 1

In [ ]:
training_dataset = [

    (array([0,0,1]), 0),

    (array([0,1,1]), 1),

    (array([1,0,1]), 1),

    (array([1,1,1]), 1),

]

In [ ]:
weights = random.rand(3)

In [ ]:
error = []

learning_rate = 0.2

n = 100

In [ ]:
for j in range(n):

    x, expected = choice(training_dataset)

    result = dot(weights, x)

    err = expected-step_function(result)

    error.append(err)

    weights += learning_rate * err * x

In [ ]:
for x, _ in training_dataset:

    result = dot(x, weights)

    print(result, step_function(result))

-0.028369951014853123 0
0.7181094652806241 1
0.20946138519794216 1
0.9559408014934194 1
